# Sequência candidata do promotor (extraída do MethPrimer)
SEQUENCIA_1 = (
    """"
    TGCCACCACGCCCGGCTAATTTTTGTATTTTTGGTAGAAACAGGGTTTCA
    ACATGTTGGCCAGGCTGGTCTCGAACTCCTGGCCTCCAGGGCTTCCACCA
    CGTAGATGCAGAAGAATATGGAGTCCAAGGCCATGAAGTACCACTCTGCA
    GGGACACAGGGGTGCGCTCAGGGCTGTCCCCAGCACCCAGTGCCCTCTCT
    CTCCTCAGCATGAGCCTCACACAAGCCCGGATTCCCAGGCTCTCTCCAGC
    TCTGGGTAAGCAGCTGCGCGACTTCACTACTGCTCTATGTCTCAGTTTTG
    TTGTCTTTAAAATGGGCATAATTGTGGCCAGAAGCAATGGCTCACACCTG
    TAATCCCAGCACTTTGGGAGGTTGAGGCAGGCGGATCACTGGAGGCCAGG
    AGTTTGAGACCAGCCTGGCCAGCAAATCCCCAACAGGCTGGTCCTGTGCC
    TTCTGTGGCAGGGGCCAGCCTGTTGGGGATTTGGAGTTGGCTTCTGGGGA
    TCCTGAGGGCTCCCACTCCTATGCCTCCATGCCTTTCTTTGCTCACGTGG
    CAACTTACATATGGAAAACCCACCCTCCTCATCATCCCATCCTCTTGGTA
    AACTTATCCTCTCCCTTTCAGGTCCTGATGAAATGTTCCCTCCTCTGGGC
    TGCCTTTCCTGTCCCCATTTAATAACACACTTGCCCCTCTCTGCTTGTTC
    CTGAGACTGTTGTCATATTTTGTTTGTTGTTGTTGTTGTTTTCTGAGATG
    GAGTCTCGCTCTGTTGCCCAGGCTGGAGTGCAGTATCGTGATCTCGGCTC
    ACTACAACCTCCGCCTCCCAGCTTCAAGAGATTCTCCTGCCTCACCCTCC
    TGTGTAGCCAGGATTACAGGCACGCACCACCACACCCGGCTAATTTTTGT
    ATTTTTTTGGTAGAGACAGGGTTTTGCCATATTGGCCAGGCTGGTCTCCA
    ACTCCTGACCTCAAGCAATCTACCTACCTTGGACTCCCAAAATGTTAGGA
    TTACAGATGTGAGCCATCGCACCCAGCCTATTTGTTTTTTTTTTTTTTTT
    TTTTTTTTCCTACGGAGTCTTGCACTGTCACCCCGGCCGGAGTGCAGTGG
    CACGATCTCGGCTCACTGCAACCTCTGCCTCCTGGGTTCAAGCGATTCTC
    CTGCCTCAGCCTCCCAAGTAGCTGGGATTACAGGGGTGCACCACCACGCC
    CAGCTAATTTTTGTATTTTTTTGGTAAAGACGGGATCTCGCCATGTTGGC
    CAGGCTGGTCTTGAACTCCTGACCTCAAGCGATCCACCCACCTCGGCCTC
    CCAAAGTGCTGAGATTACAGGCGTGAGTCACCGCGCCTGGCCTGTTGTCA
    TGTTTATTGAACTACTAGGAAGAAAGTTTGGTGGCGTATGAGCTAAAGGC
    CATGGTCCCTCCTTGCCCTCCAATAAGGCCCTCATTCAGGCATTAGTTCC
    TAATCTCTGTTCTCAAGCAGCTCACAGGTGAGTGGGAGAAATCTGGACAG
    ATAGAATCCACCATGGTAAATGTTCTGAGGGCAGGCCCCGAGCACAGGAT
    GATCTGTGGTCAGCTAAGTGACCACTCCTAGTTTTGGGCCCCTCGAGGGC
    AGCGACTGTGTTGAATTTTTCCCCATGCTGCCATGGCCCAGGCAGGCCAC
    ACACCCACATTGGATGAGTATCAATGTTTGACTGGTAGACATATGAATAA
    ATAAGGCAGTGACTGAATGAACAAACACCTCATGGCCTAAAGAGGTACAT
    AATTCAAGGAATAAAAGATGGGACCATGAACAGTCAGGAGAGTGAATAGC
    CAGTGGGGGACCTGTGCAGGAGGGTCGGGCCTTACGATCTGCGGAAGGAC
    AGTGCGGGGCCGAGATCAGGTCTGGATCCTGCGCCAGGCAGCAGGAGTTG
    GCATGGGGGGCCCAGCAAAGACTCACTTTTGCGTTTCTGAAATTGCCCTT
    CTTCTTTGCCCCAGTCTTCTGAATGTTTGGTGGAGATATCCTGGGTATGG
    ACTTTTTTGGACATCTGGGTGACACGTGAGCGGATTGTGCTGGAGGACCG
    AGTCATGCTGTGAGCCGAGCCCCGTGGGTGTGCTACGTGATAGGGGAAGA
    CTCCTGTACGAGAAGCAGCAGGGCCGGGGGCATCGTGAATCAGGCTCCGG
    GATGTGTGTGGGATAGAGAGTTGGGAAGTGCTCTGGACGTAGTCGCCATG
    GAGGTAACTGGAATGATACGCGCCGTGGTGGTCTTGGTGCTGATGGTAGT
    CTCGGTGCCGGTGGGTCTGGTGGTAGTGGTGCTGTGTGTGGTGGGGATGG
    TCGCCATGGTGGTACTCACTGGGGTGGTGATCACCTTGGTGGTACTCGCT
    GTGATAGTCAGATATCCCACGCTGGTAGGACCCCACAGAGGAATGAGGGG
    AAATGGTCTCTCCGTGATGAGGAGACTTTCCATGCTGGTGGGCTTCATGA
    TGACGGGACCTGCCATGGTGGTGGACTTGGTGATGGTGGGGCCAGCCACG
    GTGGGGGACTTGGTGATGCTGGGACTCATCGTGTTGGAGCCCGCTAAGGT
    GGGAAGCCTCGCTGTGGTGGAAGGACTCACTGTAGGGATTGGGTCCATGG
    GGGAGGTAGGACCCACCATGGTGGGAAGCCTCACCGTGGTGGGGCACGCC
    AGAGGAATAGTGGGATAAATTCTCACCGAGATATTGGGGTCTGCCATGGT
    GAGACCCCCTATGGTAATGGGAGTCACTCTGCTGATGGAACCCACCGTAT
    TGGGACCCATCATGATGCCTCCTGCCATCACGTTGGAGCTCATCATGGTA
    GTCCTCACCGTAGGAACGGTGGGAGGGGACGGCGCCTTGAGAGGGAGCCA
    GACCAAAGCCTGTGGGGCCATGGGCTCTGCCGTGATTCCGTGCCTCGCTG
    TGGTGGTGAGATTGGTGGACATGGGAGGACAAGGCTTGGTCGTGGAAGTC
    TTGGAACTCCGGAGGGTGGTGAGATTCACCACGTTGGTGGGGCACGCCGT
    GATGGTGCAACTCGTAATGGTGGAGAGCTCTGCTGTGGCCTGGCCTGTGG
    TGTGGGGGTGATGAGTGAGAGCGAAAGAACCTATCTGCGTTATTGGTGTC
    TGCCTCATTCTGAGCCTTTTCAGGCACTGAGTTTTGATCCATGACTGTGC
    TGGGAACTCTGGAGCCAAAAGAGCTCAAGACCTGGGCCCAACAGGCCCCG
    CCTGGATTTCCCTTCTTTCCTGAGCCAAGCTCAATGCAGACTGTGGCACT
    GGGCTTCCAGAAAGGCCTGACTATTCTCGTGGAACTCTCCCCTCTATGAT
    GTCACCAGCAGGCCAGGGCCTCATTCCCAAATGCCTCTTCCTGGGCTATA
    GTTCGGAATCAAGAATTATTGTGTCAAACTCCTTCATTGTAAATGAGGAA
    ACCGAGGTCAAGAAAAGGGAAGGACTAGACCAAGGTGACCTCACAGGTCA
    CTGGCAAAGCTGGACAAAGAAGTCCATGGGGGCGCCATGGCTTCATCAGC
    TACTTTAGCCCTGTTGTTGGAAAGAAAATGGTCCAAGTGGTCCAGTCTTC
    AGTCCCATCTAGAGATCAGCTGGCTCTGGGGTGAAGACTGCCTGACTCCC
    TCATAAGTAGGTGTGTGACCTTGGGCTTGTTGCTGAACTTTCCCGTGCCT
    CAGTTTCTTCCTCTGTAAAATGGGAATAATAATACCTAGCCCACAGGATC
    AAAAAAGTTAAGATATGTAAGCCTTATATTAACAGCATAATACATGGTTT
    TTGTTGTTGTTGTTGTTGTTTGTTTCTTTGTTTGTTTTTGAGATGGAGTC
    TCGCTCTGTCGCCCAGGCTGGAGTGCAGTGGCACGATCTTGACTCACTGC
    AACCTCCACCTCCCAGCTTCATGCCATTTTCCTGCCTCAGCCTCCCAAGT
    AGCTGGGACTACAGGCGCCCACCACCACGCCCGGCTAACTTTTTCTATTT
    TTAGTAGAGACGGGGTTTCACCATGTTAGCCAGAATGGTCTTGATCTCCT
    G
    """
)

# Sequência candidata do promotor (extraída do MethPrimer)
SEQUENCIA_2 = (
    """
    TCTCCATGGGAACAGGACTCCCTGGCTCTTACCGCCCCGGATCTCGACTT
    CAGCGAAGGTCTGGGCCACCAGCATGACGGTGTTGAGGCAGACAACGAAG
    AAGATGAAAGTTTCAAAGGCCAAGGATTGGGTCAGGTTCCGGATCATTTC
    CCGGAAGCCCTGAATGAGGAAGGTTAGCTTTTCCCACAGCCACTGGAAGA
    GATTGGTAGAGTGTCCCTTCTTGCGGGTCCGCTGGAGCCGGCCGGCTGAA
    AGGAACAGGGCCAGAAAGTCAAGTGTGTGCAAGAGGGGACACGAGGTCCC
    AGGCACCCCCCAGCCTGGCTCAGCGTCCATGGTCACTCCTGCCTGCTTGC
    TGGCCCTCTGCCTCCCGGGTTCAAGCAACTCTTGTGCCTCAGCCTCCCAA
    GTAGCTGGGACTGCAGGTGCCTGCCACCACGCCCGGCTAATTTTTGTATT
    TTTGGTAGAAACAGGGTTTCAACATGTTGGCCAGGCTGGTCTCGAACTCC
    TGGCCTCCAGGGCTTCCACCACGTAGATGCAGAAGAATATGGAGTCCAAG
    GCCATGAAGTACCACTCTGCAGGGACACAGGGGTGCGCTCAGGGCTGTCC
    CCAGCACCCAGTGCCCTCTCTCTCCTCAGCATGAGCCTCACACAAGCCCG
    GATTCCCAGGCTCTCTCCAGCTCTGGGTAAGCAGCTGCGCGACTTCACTA
    CTGCTCTATGTCTCAGTTTTGTTGTCTTTAAAATGGGCATAATTGTGGCC
    AGAAGCAATGGCTCACACCTGTAATCCCAGCACTTTGGGAGGTTGAGGCA
    GGCGGATCACTGGAGGCCAGGAGTTTGAGACCAGCCTGGCCAGCAAATCC
    CCAACAGGCTGGTCCTGTGCCTTCTGTGGCAGGGGCCAGCCTGTTGGGGA
    TTTGGAGTTGGCTTCTGGGGATCCTGAGGGCTCCCACTCCTATGCCTCCA
    TGCCTTTCTTTGCTCACGTGGCAACTTACATATGGAAAACCCACCCTCCT
    CATCATCCCATCCTCTTGGTAAACTTATCCTCTCCCTTTCAGGTCCTGAT
    GAAATGTTCCCTCCTCTGGGCTGCCTTTCCTGTCCCCATTTAATAACACA
    CTTGCCCCTCTCTGCTTGTTCCTGAGACTGTTGTCATATTTTGTTTGTTG
    TTGTTGTTGTTTTCTGAGATGGAGTCTCGCTCTGTTGCCCAGGCTGGAGT
    GCAGTATCGTGATCTCGGCTCACTACAACCTCCGCCTCCCAGCTTCAAGA
    GATTCTCCTGCCTCACCCTCCTGTGTAGCCAGGATTACAGGCACGCACCA
    CCACACCCGGCTAATTTTTGTATTTTTTTGGTAGAGACAGGGTTTTGCCA
    TATTGGCCAGGCTGGTCTCCAACTCCTGACCTCAAGCAATCTACCTACCT
    TGGACTCCCAAAATGTTAGGATTACAGATGTGAGCCATCGCACCCAGCCT
    ATTTGTTTTTTTTTTTTTTTTTTTTTTTTCCTACGGAGTCTTGCACTGTC
    ACCCCGGCCGGAGTGCAGTGGCACGATCTCGGCTCACTGCAACCTCTGCC
    TCCTGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGATT
    ACAGGGGTGCACCACCACGCCCAGCTAATTTTTGTATTTTTTTGGTAAAG
    ACGGGATCTCGCCATGTTGGCCAGGCTGGTCTTGAACTCCTGACCTCAAG
    CGATCCACCCACCTCGGCCTCCCAAAGTGCTGAGATTACAGGCGTGAGTC
    ACCGCGCCTGGCCTGTTGTCATGTTTATTGAACTACTAGGAAGAAAGTTT
    GGTGGCGTATGAGCTAAAGGCCATGGTCCCTCCTTGCCCTCCAATAAGGC
    CCTCATTCAGGCATTAGTTCCTAATCTCTGTTCTCAAGCAGCTCACAGGT
    GAGTGGGAGAAATCTGGACAGATAGAATCCACCATGGTAAATGTTCTGAG
    GGCAGGCCCCGAGCACAGGATGATCTGTGGTCAGCTAAGTGACCACTCCT
    AGTTTTGGGCCCCTCGAGGGCAGCGACTGTGTTGAATTTTTCCCCATGCT
    GCCATGGCCCAGGCAGGCCACACACCCACATTGGATGAGTATCAATGTTT
    GACTGGTAGACATATGAATAAATAAGGCAGTGACTGAATGAACAAACACC
    TCATGGCCTAAAGAGGTACATAATTCAAGGAATAAAAGATGGGACCATGA
    ACAGTCAGGAGAGTGAATAGCCAGTGGGGGACCTGTGCAGGAGGGTCGGG
    CCTTACGATCTGCGGAAGGACAGTGCGGGGCCGAGATCAGGTCTGGATCC
    TGCGCCAGGCAGCAGGAGTTGGCATGGGGGGCCCAGCAAAGACTCACTTT
    TGCGTTTCTGAAATTGCCCTTCTTCTTTGCCCCAGTCTTCTGAATGTTTG
    GTGGAGATATCCTGGGTATGGACTTTTTTGGACATCTGGGTGACACGTGA
    GCGGATTGTGCTGGAGGACCGAGTCATGCTGTGAGCCGAGCCCCGTGGGT
    GTGCTACGTGATAGGGGAAGACTCCTGTACGAGAAGCAGCAGGGCCGGGG
    GCATCGTGAATCAGGCTCCGGGATGTGTGTGGGATAGAGAGTTGGGAAGT
    GCTCTGGACGTAGTCGCCATGGAGGTAACTGGAATGATACGCGCCGTGGT
    GGTCTTGGTGCTGATGGTAGTCTCGGTGCCGGTGGGTCTGGTGGTAGTGG
    TGCTGTGTGTGGTGGGGATGGTCGCCATGGTGGTACTCACTGGGGTGGTG
    ATCACCTTGGTGGTACTCGCTGTGATAGTCAGATATCCCACGCTGGTAGG
    ACCCCACAGAGGAATGAGGGGAAATGGTCTCTCCGTGATGAGGAGACTTT
    CCATGCTGGTGGGCTTCATGATGACGGGACCTGCCATGGTGGTGGACTTG
    GTGATGGTGGGGCCAGCCACGGTGGGGGACTTGGTGATGCTGGGACTCAT
    CGTGTTGGAGCCCGCTAAGGTGGGAAGCCTCGCTGTGGTGGAAGGACTCA
    CTGTAGGGATTGGGTCCATGGGGGAGGTAGGACCCACCATGGTGGGAAGC
    CTCACCGTGGTGGGGCACGCCAGAGGAATAGTGGGATAAATTCTCACCGA
    GATATTGGGGTCTGCCATGGTGAGACCCCCTATGGTAATGGGAGTCACTC
    TGCTGATGGAACCCACCGTATTGGGACCCATCATGATGCCTCCTGCCATC
    ACGTTGGAGCTCATCATGGTAGTCCTCACCGTAGGAACGGTGGGAGGGGA
    CGGCGCCTTGAGAGGGAGCCAGACCAAAGCCTGTGGGGCCATGGGCTCTG
    CCGTGATTCCGTGCCTCGCTGTGGTGGTGAGATTGGTGGACATGGGAGGA
    CAAGGCTTGGTCGTGGAAGTCTTGGAACTCCGGAGGGTGGTGAGATTCAC
    CACGTTGGTGGGGCACGCCGTGATGGTGCAACTCGTAATGGTGGAGAGCT
    CTGCTGTGGCCTGGCCTGTGGTGTGGGGGTGATGAGTGAGAGCGAAAGAA
    CCTATCTGCGTTATTGGTGTCTGCCTCATTCTGAGCCTTTTCAGGCACTG
    AGTTTTGATCCATGACTGTGCTGGGAACTCTGGAGCCAAAAGAGCTCAAG
    ACCTGGGCCCAACAGGCCCCGCCTGGATTTCCCTTCTTTCCTGAGCCAAG
    CTCAATGCAGACTGTGGCACTGGGCTTCCAGAAAGGCCTGACTATTCTCG
    TGGAACTCTCCCCTCTATGATGTCACCAGCAGGCCAGGGCCTCATTCCCA
    AATGCCTCTTCCTGGGCTATAGTTCGGAATCAAGAATTATTGTGTCAAAC
    TCCTTCATTGTAAATGAGGAAACCGAGGTCAAGAAAAGGGAAGGACTAGA
    CCAAGGTGACCTCACAGGTCACTGGCAAAGCTGGACAAAGAAGTCCATGG
    GGGCGCCATGGCTTCATCAGCTACTTTAGCCCTGTTGTTGGAAAGAAAAT
    GGTCCAAGTGGTCCAGTCTTCAGTCCCATCTAGAGATCAGCTGGCTCTGG
    G
    """
)


# ________________________________________________________________
#seq = SEQUENCIA_1 # Análise da sequência 1
seq = SEQUENCIA_2 # Análise da sequência 2

# Mapeamento de todos os CpGs
cpgs = [i for i in range(len(seq) - 1) if seq[i] == 'C' and seq[i+1] == 'G']
print(f"Total de CpGs: {len(cpgs)}")
print(f"Posições: {cpgs}\n")
 
# Identificação de clusters (>=3 CpGs dentro de janela de 30 pb)
JANELA = 30
MIN_CPG = 3
clusters = []
for i, pos in enumerate(cpgs):
    grupo = [p for p in cpgs if pos <= p <= pos + JANELA]
    if len(grupo) >= MIN_CPG:
        clusters.append(grupo)
 
# Remoção de duplicatas e ordenação por densidade
vistos = set()
unicos = []
for c in clusters:
    chave = tuple(c)
    if chave not in vistos:
        vistos.add(chave)
        unicos.append(c)
 
unicos.sort(key=lambda x: len(x), reverse=True)
 
print("=== Clusters candidatos para posicionamento do gRNA ===")
for i, c in enumerate(unicos[:5]):
    centro = (c[0] + c[-1]) // 2
    print(f"\nCluster {i+1}: {len(c)} CpGs | posições {c[0]}–{c[-1]} | centro ~{centro}")
    print(f"  Sequência local: {seq[c[0]-5:c[-1]+6]}")
    print(f"  → Posicionar gRNA centrado em ~{centro} pb")